// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9CnzQkfFxs7zVbdEugfXyNVISaN6hXw',
    appId: '1:776229748935:web:5444bd360b7e88aa6b3ee2',
    messagingSenderId: '776229748935',
    projectId: 'wager-80a1f',
    authDomain: 'wager-80a1f.firebaseapp.com',
    storageBucket: 'wager-80a1f.appspot.com',
    measurementId: 'G-1DZPVT7C80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHdDF7ci2wQWcUR6_Nk59tTEjJI2EOco',
    appId: '1:776229748935:android:3758e855943fb32a6b3ee2',
    messagingSenderId: '776229748935',
    projectId: 'wager-80a1f',
    storageBucket: 'wager-80a1f.appspot.com',
  );
}
