# This is a basic workflow to help you get started with Actions

name: Flutter Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - working-directory: ./app
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Download Packages
    - run: flutter pub get
    - name: IOS Build
    - run: flutter build ios --release --no-codesign
    - name: Android Build
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Web Build
    - run: flutter build web
