name: Services Build

on:
    push:
        paths:
            - "services/**"
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

defaults:
    run:
        working-directory: ./services

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js v16.x
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
            - run: npm ci
            - run: npm run build
